### ISSUE TITLE
桌面组件设置问题

### ISSUE THREAD

**Issue by MengNianxiaoyao** [feilongproject/BAAssestDownloader#1]
在iqooneo5中，添加组件弹出设置界面时，出现保存设置直接闪退的情况

**Comment by feilongproject** [comment]
我使用全版本的原生 Android 都能够测试成功，但是因为 Android 底层 api 在不同手机系统上会被不同程度魔改，并且我手上没有此种手机，请遵循新的 issues BUG 反馈模板，记录下系统日志后我才能诊断问题
