### ISSUE TITLE
桌面组件设置问题

### ISSUE THREAD

**Issue by MengNianxiaoyao** [feilongproject/BAAssestDownloader#2]
### 在提问之前

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我已使用最新版，并且使用最新版时该 bug 仍然未被修复

### 问题描述

在iqooneo5中，添加组件弹出设置界面时，出现保存设置直接闪退的情况

### 系统信息

- 安卓版本：13
- 系统版本：os3
- 手机型号：iqooneo5

### 复现步骤

将组件拖动到桌面后进入设置界面，选择服务器后点击保存直接闪退

### 日志文件

[log.txt](https://github.com/feilongproject/BAAssetsDownloader/files/12506156/log.txt)

**Comment by feilongproject** [comment]
经过确认已经找到原因了，根据日志中反馈，图片分辨率所占用的空间为 `769280(长宽乘积) * 32 = 24616960`，超过系统所设定的 `15552000` 大小，从而导致 `RemoteViews` 内存溢出问题。

具体修复办法要尝试多个可能的选项，在权衡一系列条件之后，找出合适的结果，大约会在一天之内修复。

**Comment by feilongproject** [comment]
现在使用 `Glide` 作为图像加载框架，请从[此链接](https://dl.schale.top/baad/develop)下载 dev 版，若无报错或 24 小时未回复，该 issue 将会被关闭

**Comment by MengNianxiaoyao** [comment]
> 现在使用 `Glide` 作为图像加载框架，请从[此链接](https://dl.schale.top/baad/develop)下载 dev 版，若无报错或 24 小时未回复，该 issue 将会被关闭

~无报错，组件功能正常了~

**Comment by MengNianxiaoyao** [comment]
偶现组件背景不显示，不知道什么原因。因为是偶现，比较难复现获得log

**Comment by MengNianxiaoyao** [comment]
现在已知的情况是息屏一段时间再亮屏，组件背景就不显示，不知道是不是透明度有问题还是什么。这种情况导致模糊度调节也出问题，一旦从无模糊调到其他模糊度，就调不回来了

**Comment by feilongproject** [comment]
新问题已转移到 https://github.com/feilongproject/BAAssetsDownloader/issues/3
